name: Jekyll CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4-asan' # Specify your Jekyll's Ruby version
          bundler-cache: true # Installs gems with Bundler
      - name: Expose Secrets as Environment Variables
        run: |
          echo "GTM_CONTAINER_ID=${{ secrets.GTM_CONTAINER_ID }}" >> $GITHUB_ENV
      - name: Build Jekyll site
        run: bundle exec jekyll build
