name: Jekyll CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Specify your Jekyll's Ruby version
          bundler-cache: true # Installs gems with Bundler
      - run: gem install bundler
      - run: bundle install
      - name: Build Jekyll site
        env:
          GTM_CONTAINER_ID: ${{ secrets.GTM_CONTAINER_ID }}
        run: bundle exec jekyll build
