name: Jekyll CIon: [push]

jobs:
  build:
    runs-on: ubuntu-lateststeps:
      - uses: actions/checkout@v4- name: SetupRubyuses: ruby/setup-ruby@v1
with:
          ruby-version: '3.x' # Specifyyour Jekyll's Ruby version
          bundler-cache: true #Installs gems with Bundler
      - name: Expose Secrets as Environment Variables 
run: |
          echo"GTM_CONTAINER_ID=${{ secrets.GTM_CONTAINER_ID}}" >> $GITHUB_ENV
      - name: Build Jekyll siterun: bundleexecjekyll build
